apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  KAFKA_TOPIC: "location-events"
  KAFKA_SERVER: "kafka-service:9092"
metadata:
  name: db-env